package PHONEPE;

import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

// ═══════════════════════════════════════════════════════════════════════
//  USER
// ═══════════════════════════════════════════════════════════════════════
class User {
    private static long idCounter = 1001;
    String userId, mobile, name;
    double balance;
    boolean isVIP;

    public User(String mobile, String name, double balance, boolean isVIP) {
        this.userId = "U" + idCounter++;
        this.mobile = mobile; this.name = name;
        this.balance = balance; this.isVIP = isVIP;
    }
    public User(String userId, String mobile, String name, double balance, boolean isVIP) {
        this.userId = userId; this.mobile = mobile; this.name = name;
        this.balance = balance; this.isVIP = isVIP;
        try { long n = Long.parseLong(userId.substring(1)); if (n >= idCounter) idCounter = n+1; } catch (Exception ignored) {}
    }
    public String toCSV() { return userId+","+mobile+","+name+","+balance+","+isVIP; }
    public String toString() {
        return String.format("[%s] %-18s  Mobile: %-13s  Balance: Rs.%-12.2f  %s",
                userId, name, mobile, balance, isVIP ? "VIP" : "Regular");
    }
}

// ═══════════════════════════════════════════════════════════════════════
//  TRANSACTION
// ═══════════════════════════════════════════════════════════════════════
class Transaction {
    private static long txnCounter = 1;
    String txnId, type, fromMobile, toMobile, timestamp;
    double amount;
    boolean undone;

    public Transaction(String type, String fromMobile, String toMobile, double amount) {
        this.txnId = "TXN" + String.format("%06d", txnCounter++);
        this.type = type; this.fromMobile = fromMobile; this.toMobile = toMobile;
        this.amount = amount; this.undone = false;
        this.timestamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
    }
    public Transaction(String txnId, String type, String fromMobile, String toMobile,
                       double amount, String timestamp, boolean undone) {
        this.txnId = txnId; this.type = type; this.fromMobile = fromMobile;
        this.toMobile = toMobile; this.amount = amount;
        this.timestamp = timestamp; this.undone = undone;
        try { long n = Long.parseLong(txnId.substring(3)); if (n >= txnCounter) txnCounter = n+1; } catch (Exception ignored) {}
    }
    public String toCSV() { return txnId+","+type+","+fromMobile+","+toMobile+","+amount+","+timestamp+","+undone; }
    public String toString() {
        return String.format("  %-12s %-10s  %-13s -> %-13s  Rs.%-10.2f  %s%s",
                txnId, type, fromMobile, toMobile, amount, timestamp, undone ? " [REVERSED]" : "");
    }
}

// ═══════════════════════════════════════════════════════════════════════
//  REWARD  - Rs.1 to Rs.100 cashback on every 1000th transaction
// ═══════════════════════════════════════════════════════════════════════
class Reward {
    String rewardId, mobile, userName, timestamp;
    double amount;
    long triggerCount;

    public Reward(String mobile, String userName, double amount, long triggerCount) {
        this.rewardId = "RWD" + String.format("%05d", triggerCount / 1000);
        this.mobile = mobile; this.userName = userName;
        this.amount = amount; this.triggerCount = triggerCount;
        this.timestamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
    }
    public Reward(String rewardId, String mobile, String userName,
                  double amount, long triggerCount, String timestamp) {
        this.rewardId = rewardId; this.mobile = mobile; this.userName = userName;
        this.amount = amount; this.triggerCount = triggerCount; this.timestamp = timestamp;
    }
    public String toCSV() { return rewardId+","+mobile+","+userName+","+amount+","+triggerCount+","+timestamp; }
    public String toString() {
        return String.format("  %-10s  %-18s  Rs.%-8.2f  (at txn #%d)  %s",
                rewardId, userName, amount, triggerCount, timestamp);
    }
}

// ═══════════════════════════════════════════════════════════════════════
//  GIFT CARD  - generated by user or SYSTEM, redeemed once only
//  Status: ACTIVE | REDEEMED | EXPIRED
// ═══════════════════════════════════════════════════════════════════════
class GiftCard {
    String code, createdBy, redeemedBy, status, createdAt, redeemedAt;
    double amount;

    public GiftCard(double amount, String createdBy) {
        this.code = generateCode(); this.amount = amount;
        this.createdBy = createdBy; this.redeemedBy = "NONE";
        this.status = "ACTIVE"; this.redeemedAt = "N/A";
        this.createdAt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
    }
    public GiftCard(String code, double amount, String createdBy, String redeemedBy,
                    String status, String createdAt, String redeemedAt) {
        this.code = code; this.amount = amount; this.createdBy = createdBy;
        this.redeemedBy = redeemedBy; this.status = status;
        this.createdAt = createdAt; this.redeemedAt = redeemedAt;
    }
    private String generateCode() {
        String ch = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
        Random r = new Random();
        String p1 = "", p2 = "";
        for (int i = 0; i < 4; i++) p1 += ch.charAt(r.nextInt(ch.length()));
        for (int i = 0; i < 4; i++) p2 += ch.charAt(r.nextInt(ch.length()));
        return "GIFT-" + p1 + "-" + p2;
    }
    public String toCSV() { return code+","+amount+","+createdBy+","+redeemedBy+","+status+","+createdAt+","+redeemedAt; }
    public String toString() {
        String extra = status.equals("REDEEMED") ? "  Redeemed by: "+redeemedBy+" at "+redeemedAt : "";
        return String.format("  %-18s  Rs.%-8.2f  [%-8s]  Created: %s%s",
                code, amount, status, createdAt, extra);
    }
}

// ═══════════════════════════════════════════════════════════════════════
//  PHONEPE APP
// ═══════════════════════════════════════════════════════════════════════
public class PhonePeApp {

    // DS 1: HashMap  - O(1) user lookup
    private final HashMap<String, User>     userMap       = new HashMap<>();
    // DS 2: Queue    - FIFO transfer processing
    private final Queue<Transaction>        transferQueue = new LinkedList<>();
    // DS 3: Stack    - LIFO undo
    private final Stack<Transaction>        undoStack     = new Stack<>();
    // DS 4: ArrayList - ordered transaction history
    private final ArrayList<Transaction>    txnHistory    = new ArrayList<>();
    // Gift cards keyed by code
    private final HashMap<String, GiftCard> giftCards     = new HashMap<>();
    // Reward history
    private final ArrayList<Reward>         rewardLog     = new ArrayList<>();

    private long globalTxnCount = 0;   // drives reward trigger

    private static final String USERS_FILE    = "PhonePe_Users.csv";
    private static final String TXN_FILE      = "PhonePe_Transactions.csv";
    private static final String REWARDS_FILE  = "PhonePe_Rewards.csv";
    private static final String GIFTCARD_FILE = "PhonePe_GiftCards.csv";
    private static final long   REWARD_EVERY  = 1000;

    private final Random random = new Random();

    // ───────────────────────────────────────────────────────────────────
    //  RESOLVE USER
    //  Priority: 1) userId  2) mobile  3) exact name  4) partial name
    // ───────────────────────────────────────────────────────────────────
    public User resolveUser(String input) {
        if (input == null || input.trim().isEmpty()) {
            System.out.println("  X Input cannot be empty."); return null; }
        input = input.trim();
        String lower = input.toLowerCase();

        if (input.matches("(?i)U\\d+"))
            for (User u : userMap.values())
                if (u.userId.equalsIgnoreCase(input)) return u;

        if (input.matches("\\d+")) {
            User u = userMap.get(input); if (u != null) return u; }

        for (User u : userMap.values())
            if (u.name.trim().equalsIgnoreCase(lower)) return u;

        for (User u : userMap.values())
            if (u.name.trim().toLowerCase().contains(lower)) return u;

        System.out.println("  X No user found for: \"" + input + "\"");
        return null;
    }

    // ───────────────────────────────────────────────────────────────────
    //  REWARD ENGINE
    //  Called after every committed transaction.
    //  Every REWARD_EVERY (1000) transactions -> Rs.1-100 cashback.
    // ───────────────────────────────────────────────────────────────────
    private void commitAndCheckReward(User beneficiary) {
        globalTxnCount++;
        if (globalTxnCount % REWARD_EVERY == 0) {
            double amt = Math.round((1.0 + random.nextDouble() * 99.0) * 100.0) / 100.0;
            beneficiary.balance += amt;

            Reward r = new Reward(beneficiary.mobile, beneficiary.name, amt, globalTxnCount);
            rewardLog.add(r);
            appendRewardToCSV(r);

            // Reward itself is also a transaction
            Transaction rt = new Transaction("REWARD", "SYSTEM", beneficiary.mobile, amt);
            txnHistory.add(rt);
            appendTxnToCSV(rt);

            System.out.println();
            System.out.println("  ***************************************************");
            System.out.printf ("  *   REWARD UNLOCKED!  Transaction #%d%n", globalTxnCount);
            System.out.printf ("  *   Rs.%.2f cashback credited to %s%n", amt, beneficiary.name);
            System.out.println("  ***************************************************");
        }
    }

    // ───────────────────────────────────────────────────────────────────
    //  GIFT CARD - Generate
    //  Creator can be a user (amount deducted) or SYSTEM (free issue).
    // ───────────────────────────────────────────────────────────────────
    public void generateGiftCard(String creatorInput, double amount) {
        if (amount <= 0) { System.out.println("  X Amount must be > 0."); return; }

        boolean sysGen = creatorInput.equalsIgnoreCase("SYSTEM");
        User creator = null;

        if (!sysGen) {
            creator = resolveUser(creatorInput);
            if (creator == null) return;
            if (creator.balance < amount) {
                System.out.printf("  X Insufficient balance. Available: Rs.%.2f%n", creator.balance); return; }
            creator.balance -= amount;
            Transaction t = new Transaction("DEBIT", creator.mobile, "GIFTCARD", amount);
            txnHistory.add(t); appendTxnToCSV(t);
            commitAndCheckReward(creator);
            saveUsersCSV();
        }

        GiftCard gc = new GiftCard(amount, sysGen ? "SYSTEM" : creator.mobile);
        giftCards.put(gc.code, gc);
        saveGiftCardsCSV();

        System.out.println();
        System.out.println("  +--------------------------------------------+");
        System.out.println("  |          GIFT CARD GENERATED               |");
        System.out.printf ("  |  Code   : %-30s  |%n", gc.code);
        System.out.printf ("  |  Amount : Rs.%-27.2f  |%n", gc.amount);
        System.out.printf ("  |  By     : %-30s  |%n", sysGen ? "SYSTEM" : creator.name);
        System.out.println("  |  Status : ACTIVE                           |");
        System.out.println("  |  Share code to let someone redeem it.      |");
        System.out.println("  +--------------------------------------------+");
    }

    // ───────────────────────────────────────────────────────────────────
    //  GIFT CARD - Redeem
    //  Code validated -> ACTIVE check -> credit wallet -> mark REDEEMED
    // ───────────────────────────────────────────────────────────────────
    public void redeemGiftCard(String redeemerId, String code) {
        User redeemer = resolveUser(redeemerId);
        if (redeemer == null) return;

        GiftCard gc = giftCards.get(code.trim().toUpperCase());
        if (gc == null)                        { System.out.println("  X Invalid gift card code."); return; }
        if (!gc.status.equals("ACTIVE"))       { System.out.printf("  X Card is %s.%n", gc.status); return; }
        if (gc.createdBy.equals(redeemer.mobile)) { System.out.println("  X Cannot redeem your own gift card."); return; }

        redeemer.balance += gc.amount;
        gc.status     = "REDEEMED";
        gc.redeemedBy = redeemer.mobile;
        gc.redeemedAt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());

        Transaction t = new Transaction("GIFTCARD", "GIFTCARD", redeemer.mobile, gc.amount);
        txnHistory.add(t); undoStack.push(t); appendTxnToCSV(t);
        commitAndCheckReward(redeemer);
        saveUsersCSV(); saveGiftCardsCSV();

        System.out.println();
        System.out.println("  +--------------------------------------------+");
        System.out.println("  |          GIFT CARD REDEEMED!               |");
        System.out.printf ("  |  Code   : %-30s  |%n", gc.code);
        System.out.printf ("  |  Amount : Rs.%-27.2f  |%n", gc.amount);
        System.out.printf ("  |  To     : %-30s  |%n", redeemer.name);
        System.out.printf ("  |  Balance: Rs.%-27.2f  |%n", redeemer.balance);
        System.out.println("  +--------------------------------------------+");
    }

    // ───────────────────────────────────────────────────────────────────
    //  GIFT CARD - Views
    // ───────────────────────────────────────────────────────────────────
    public void showGiftCards(boolean activeOnly) {
        System.out.println("\n  +- Gift Cards " + (activeOnly ? "(ACTIVE only)" : "(all)") + " -----");
        boolean any = false;
        for (GiftCard gc : giftCards.values())
            if (!activeOnly || gc.status.equals("ACTIVE")) { System.out.println(gc); any = true; }
        if (!any) System.out.println("  (none)");
        System.out.println("  +-------------------------------------------------");
    }

    public void showMyGiftCards(String identifier) {
        User u = resolveUser(identifier); if (u == null) return;
        System.out.println("\n  +- My Gift Cards: " + u.name + " -----");
        boolean any = false;
        for (GiftCard gc : giftCards.values())
            if (gc.createdBy.equals(u.mobile) || gc.redeemedBy.equals(u.mobile)) { System.out.println(gc); any = true; }
        if (!any) System.out.println("  (none)");
        System.out.println("  +--------------------------------------------------");
    }

    // ───────────────────────────────────────────────────────────────────
    //  REWARD - Views
    // ───────────────────────────────────────────────────────────────────
    public void showAllRewards() {
        System.out.println("\n  +- Reward History (every " + REWARD_EVERY + "th transaction) -----");
        System.out.printf ("  Total transactions  : %d%n", globalTxnCount);
        System.out.printf ("  Next reward at txn  : #%d%n", (globalTxnCount / REWARD_EVERY + 1) * REWARD_EVERY);
        System.out.println("  -------------------------------------------------------");
        if (rewardLog.isEmpty()) System.out.println("  (no rewards issued yet)");
        else rewardLog.forEach(System.out::println);
        System.out.println("  +------------------------------------------------------");
    }

    public void showUserRewards(String identifier) {
        User u = resolveUser(identifier); if (u == null) return;
        System.out.println("\n  +- Rewards for " + u.name + " -----");
        boolean any = false;
        for (Reward r : rewardLog) if (r.mobile.equals(u.mobile)) { System.out.println(r); any = true; }
        if (!any) System.out.println("  (no rewards yet - keep transacting!)");
        System.out.println("  +-----------------------------------------");
    }

    // ═══════════════════════════════════════════════════════════════════
    //  CORE WALLET FEATURES 1-13
    // ═══════════════════════════════════════════════════════════════════

    public void registerUser(String mobile, String name, double balance, boolean isVIP) {
        if (userMap.containsKey(mobile)) { System.out.println("  X Mobile " + mobile + " already registered."); return; }
        User u = new User(mobile, name, balance, isVIP);
        userMap.put(mobile, u); appendUserToCSV(u);
        System.out.println("  OK Registered: " + u);
    }

    public void addMoney(String identifier, double amount) {
        User u = resolveUser(identifier); if (u == null) return;
        if (amount <= 0) { System.out.println("  X Amount must be > 0."); return; }
        u.balance += amount;
        Transaction t = new Transaction("CREDIT", "SYSTEM", u.mobile, amount);
        txnHistory.add(t); undoStack.push(t); appendTxnToCSV(t);
        commitAndCheckReward(u); saveUsersCSV();
        System.out.printf("  OK Rs.%.2f added to %s  |  Balance: Rs.%.2f%n", amount, u.name, u.balance);
    }

    public void enqueueSendMoney(String fromId, String toId, double amount) {
        User from = resolveUser(fromId); User to = resolveUser(toId);
        if (from == null || to == null) return;
        if (amount <= 0) { System.out.println("  X Amount must be > 0."); return; }
        if (from.mobile.equals(to.mobile)) { System.out.println("  X Same sender/receiver."); return; }
        Transaction t = new Transaction("TRANSFER", from.mobile, to.mobile, amount);
        transferQueue.offer(t);
        System.out.printf("  OK Queued: %s -> %s  Rs.%.2f  (depth: %d)%n",
                from.name, to.name, amount, transferQueue.size());
    }

    public void processTransferQueue() {
        if (transferQueue.isEmpty()) { System.out.println("  No pending transfers."); return; }
        System.out.println("  Processing queue...");
        int ok = 0, failed = 0;
        while (!transferQueue.isEmpty()) {
            Transaction t = transferQueue.poll();
            User from = userMap.get(t.fromMobile); User to = userMap.get(t.toMobile);
            if (from == null || to == null) { System.out.printf("  X %s skipped - user deleted.%n", t.txnId); failed++; continue; }
            if (from.balance < t.amount) { System.out.printf("  X %s skipped - low balance Rs.%.2f%n", t.txnId, from.balance); failed++; continue; }
            from.balance -= t.amount; to.balance += t.amount;
            txnHistory.add(t); undoStack.push(t); appendTxnToCSV(t);
            commitAndCheckReward(to); ok++;
            System.out.printf("  OK %s  %s -> %s  Rs.%.2f%n", t.txnId, from.name, to.name, t.amount);
        }
        if (ok > 0) saveUsersCSV();
        System.out.printf("  Done - OK: %d | Failed: %d%n", ok, failed);
    }

    public void undoLastTransaction() {
        if (undoStack.isEmpty()) { System.out.println("  X Nothing to undo."); return; }
        Transaction t = undoStack.pop(); t.undone = true;
        switch (t.type) {
            case "CREDIT": {
                User u = userMap.get(t.toMobile);
                if (u != null && u.balance >= t.amount) {
                    u.balance -= t.amount;
                    System.out.printf("  OK Undone CREDIT %s - Rs.%.2f removed from %s. Balance: Rs.%.2f%n",
                            t.txnId, t.amount, u.name, u.balance);
                } else System.out.println("  X Undo failed."); break;
            }
            case "TRANSFER": {
                User from = userMap.get(t.fromMobile); User to = userMap.get(t.toMobile);
                if (from != null && to != null && to.balance >= t.amount) {
                    to.balance -= t.amount; from.balance += t.amount;
                    System.out.printf("  OK Undone TRANSFER %s - Rs.%.2f reversed.%n", t.txnId, t.amount);
                } else System.out.println("  X Undo failed."); break;
            }
            case "GIFTCARD": {
                User u = userMap.get(t.toMobile);
                if (u != null && u.balance >= t.amount) {
                    u.balance -= t.amount;
                    for (GiftCard gc : giftCards.values()) {
                        if (gc.redeemedBy.equals(u.mobile) && gc.amount == t.amount && gc.status.equals("REDEEMED")) {
                            gc.status = "ACTIVE"; gc.redeemedBy = "NONE"; gc.redeemedAt = "N/A";
                            System.out.printf("  OK Undone GIFTCARD - Rs.%.2f removed, card %s restored.%n", t.amount, gc.code);
                            break;
                        }
                    }
                    saveGiftCardsCSV();
                } else System.out.println("  X Undo failed."); break;
            }
            default: System.out.println("  X Undo not supported for: " + t.type);
        }
        saveUsersCSV(); saveTxnCSV();
    }

    public void checkBalance(String identifier) {
        User u = resolveUser(identifier); if (u == null) return;
        System.out.printf("  Balance: %-18s [%s]  Mobile: %s  ->  Rs.%.2f%n",
                u.name, u.userId, u.mobile, u.balance);
    }

    public void showUserHistory(String identifier) {
        User u = resolveUser(identifier); if (u == null) return;
        System.out.println("\n  +- History: " + u.name + " [" + u.userId + "] -----");
        boolean any = false;
        for (Transaction t : txnHistory)
            if (t.fromMobile.equals(u.mobile) || t.toMobile.equals(u.mobile)) { System.out.println(t); any = true; }
        if (!any) System.out.println("  (no transactions)");
        System.out.println("  +---------------------------------------------------");
    }

    public void showAllTransactions() {
        System.out.println("\n  +- All Transactions -----");
        if (txnHistory.isEmpty()) System.out.println("  (none)");
        else txnHistory.forEach(System.out::println);
        System.out.println("  +------------------------");
    }

    // DS 5: PriorityQueue / Max-Heap
    public void showTopKUsers(int k) {
        if (userMap.isEmpty()) { System.out.println("  No users."); return; }
        PriorityQueue<User> heap = new PriorityQueue<>((a, b) -> {
            double wa = a.balance*(a.isVIP?1.2:1.0), wb = b.balance*(b.isVIP?1.2:1.0);
            return Double.compare(wb, wa); });
        heap.addAll(userMap.values());
        int actual = Math.min(k, heap.size());
        System.out.println("\n  +- Top-" + actual + " Holders -----");
        for (int r = 1; r <= actual; r++) System.out.printf("  |  #%-3d %s%n", r, heap.poll());
        System.out.println("  +------------------");
    }

    // DS 6: Sorting (TimSort)
    public void showBalanceReport(String order) {
        if (userMap.isEmpty()) { System.out.println("  No users."); return; }
        ArrayList<User> sorted = new ArrayList<>(userMap.values());
        if (order.equalsIgnoreCase("ASC")) {
            sorted.sort(Comparator.comparingDouble(u -> u.balance));
            System.out.println("\n  +- Balance Report (Low to High) -----");
        } else {
            sorted.sort((a, b) -> Double.compare(b.balance, a.balance));
            System.out.println("\n  +- Balance Report (High to Low) -----");
        }
        for (int i = 0; i < sorted.size(); i++) System.out.printf("  |  Rank %-3d %s%n", i+1, sorted.get(i));
        System.out.println("  +-------------------------------------");
    }

    public void showAllUsers() {
        System.out.println("\n  +- All Users -----");
        if (userMap.isEmpty()) System.out.println("  (none)");
        else userMap.values().forEach(u -> System.out.println("  |  " + u));
        System.out.println("  +-----------------");
    }

    public void deleteUser(String identifier) {
        User u = resolveUser(identifier); if (u == null) return;
        userMap.remove(u.mobile); saveUsersCSV();
        System.out.println("  OK Deleted: " + u.name + " [" + u.userId + "]");
    }

    public void showPendingTransfers() {
        System.out.println("\n  +- Pending Queue -----");
        if (transferQueue.isEmpty()) System.out.println("  (empty)");
        else transferQueue.forEach(t -> System.out.printf("  |  %-12s  %-13s -> %-13s  Rs.%.2f%n",
                t.txnId, t.fromMobile, t.toMobile, t.amount));
        System.out.println("  +---------------------");
    }

    // ═══════════════════════════════════════════════════════════════════
    //  CSV PERSISTENCE
    // ═══════════════════════════════════════════════════════════════════
    private void appendUserToCSV(User u) {
        try (FileWriter fw = new FileWriter(USERS_FILE, true)) {
            if (!new File(USERS_FILE).exists() || new File(USERS_FILE).length() == 0)
                fw.write("userId,mobile,name,balance,isVIP\n");
            fw.write(u.toCSV() + "\n");
        } catch (IOException e) { System.out.println("  CSV error: " + e.getMessage()); }
    }
    public void saveUsersCSV() {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(USERS_FILE))) {
            bw.write("userId,mobile,name,balance,isVIP\n");
            for (User u : userMap.values()) { bw.write(u.toCSV()); bw.newLine(); }
        } catch (IOException e) { System.out.println("  CSV error: " + e.getMessage()); }
    }
    private void appendTxnToCSV(Transaction t) {
        try (FileWriter fw = new FileWriter(TXN_FILE, true)) {
            if (!new File(TXN_FILE).exists() || new File(TXN_FILE).length() == 0)
                fw.write("txnId,type,from,to,amount,timestamp,undone\n");
            fw.write(t.toCSV() + "\n");
        } catch (IOException e) { System.out.println("  CSV error: " + e.getMessage()); }
    }
    public void saveTxnCSV() {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(TXN_FILE))) {
            bw.write("txnId,type,from,to,amount,timestamp,undone\n");
            for (Transaction t : txnHistory) { bw.write(t.toCSV()); bw.newLine(); }
        } catch (IOException e) { System.out.println("  CSV error: " + e.getMessage()); }
    }
    private void appendRewardToCSV(Reward r) {
        try (FileWriter fw = new FileWriter(REWARDS_FILE, true)) {
            if (!new File(REWARDS_FILE).exists() || new File(REWARDS_FILE).length() == 0)
                fw.write("rewardId,mobile,userName,amount,triggerCount,timestamp\n");
            fw.write(r.toCSV() + "\n");
        } catch (IOException e) { System.out.println("  CSV error: " + e.getMessage()); }
    }
    public void saveGiftCardsCSV() {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(GIFTCARD_FILE))) {
            bw.write("code,amount,createdBy,redeemedBy,status,createdAt,redeemedAt\n");
            for (GiftCard gc : giftCards.values()) { bw.write(gc.toCSV()); bw.newLine(); }
        } catch (IOException e) { System.out.println("  CSV error: " + e.getMessage()); }
    }

    public void loadUsersCSV() {
        try (BufferedReader br = new BufferedReader(new FileReader(USERS_FILE))) {
            br.readLine();
            String line;
            while ((line = br.readLine()) != null) {
                String[] p = line.split(",", -1); if (p.length < 5) continue;
                try { User u = new User(p[0].trim(),p[1].trim(),p[2].trim(),Double.parseDouble(p[3].trim()),Boolean.parseBoolean(p[4].trim())); userMap.put(u.mobile, u); } catch (NumberFormatException ignored) {}
            }
            System.out.println("  OK Loaded " + userMap.size() + " user(s).");
        } catch (FileNotFoundException e) { System.out.println("  No user data - starting fresh.");
        } catch (IOException e) { System.out.println("  CSV error: " + e.getMessage()); }
    }
    public void loadTxnCSV() {
        try (BufferedReader br = new BufferedReader(new FileReader(TXN_FILE))) {
            br.readLine(); String line;
            while ((line = br.readLine()) != null) {
                String[] p = line.split(",", -1); if (p.length < 7) continue;
                try {
                    Transaction t = new Transaction(p[0].trim(),p[1].trim(),p[2].trim(),p[3].trim(),
                            Double.parseDouble(p[4].trim()),p[5].trim(),Boolean.parseBoolean(p[6].trim()));
                    txnHistory.add(t); if (!t.undone) undoStack.push(t); globalTxnCount++;
                } catch (NumberFormatException ignored) {}
            }
            System.out.println("  OK Loaded " + txnHistory.size() + " transaction(s). Count: " + globalTxnCount);
        } catch (FileNotFoundException e) { System.out.println("  No transaction data - starting fresh.");
        } catch (IOException e) { System.out.println("  CSV error: " + e.getMessage()); }
    }
    public void loadRewardsCSV() {
        try (BufferedReader br = new BufferedReader(new FileReader(REWARDS_FILE))) {
            br.readLine(); String line;
            while ((line = br.readLine()) != null) {
                String[] p = line.split(",", -1); if (p.length < 6) continue;
                try { rewardLog.add(new Reward(p[0].trim(),p[1].trim(),p[2].trim(),
                        Double.parseDouble(p[3].trim()),Long.parseLong(p[4].trim()),p[5].trim())); } catch (NumberFormatException ignored) {}
            }
            System.out.println("  OK Loaded " + rewardLog.size() + " reward(s).");
        } catch (FileNotFoundException e) { System.out.println("  No reward data - starting fresh.");
        } catch (IOException e) { System.out.println("  CSV error: " + e.getMessage()); }
    }
    public void loadGiftCardsCSV() {
        try (BufferedReader br = new BufferedReader(new FileReader(GIFTCARD_FILE))) {
            br.readLine(); String line;
            while ((line = br.readLine()) != null) {
                String[] p = line.split(",", -1); if (p.length < 7) continue;
                try { GiftCard gc = new GiftCard(p[0].trim(),Double.parseDouble(p[1].trim()),
                        p[2].trim(),p[3].trim(),p[4].trim(),p[5].trim(),p[6].trim());
                    giftCards.put(gc.code, gc); } catch (NumberFormatException ignored) {}
            }
            System.out.println("  OK Loaded " + giftCards.size() + " gift card(s).");
        } catch (FileNotFoundException e) { System.out.println("  No gift card data - starting fresh.");
        } catch (IOException e) { System.out.println("  CSV error: " + e.getMessage()); }
    }

    // ═══════════════════════════════════════════════════════════════════
    //  MAIN
    // ═══════════════════════════════════════════════════════════════════
    public static void main(String[] args) {
        PhonePeApp app = new PhonePeApp();
        Scanner sc = new Scanner(System.in);

        printBanner();
        app.loadUsersCSV(); app.loadTxnCSV();
        app.loadRewardsCSV(); app.loadGiftCardsCSV();

        int choice = 0;
        do {
            printMenu();
            System.out.print("  Enter choice: ");
            try {
                choice = Integer.parseInt(sc.nextLine().trim());
                System.out.println();
                switch (choice) {
                    case 1:
                        System.out.print("  Mobile            : "); String mob = sc.nextLine().trim();
                        System.out.print("  Full name         : "); String nm  = sc.nextLine().trim();
                        System.out.print("  Initial balance   : "); double b   = Double.parseDouble(sc.nextLine().trim());
                        System.out.print("  VIP? (yes/no)     : "); boolean v  = sc.nextLine().trim().equalsIgnoreCase("yes");
                        app.registerUser(mob, nm, b, v); break;
                    case 2:
                        printIdHint();
                        System.out.print("  User              : "); String id2 = sc.nextLine().trim();
                        System.out.print("  Amount            : "); double a2  = Double.parseDouble(sc.nextLine().trim());
                        app.addMoney(id2, a2); break;
                    case 3:
                        printIdHint();
                        System.out.print("  From              : "); String f3 = sc.nextLine().trim();
                        System.out.print("  To                : "); String t3 = sc.nextLine().trim();
                        System.out.print("  Amount            : "); double a3 = Double.parseDouble(sc.nextLine().trim());
                        app.enqueueSendMoney(f3, t3, a3); break;
                    case 4: app.processTransferQueue(); break;
                    case 5: app.undoLastTransaction(); break;
                    case 6: printIdHint(); System.out.print("  User              : "); app.checkBalance(sc.nextLine().trim()); break;
                    case 7: printIdHint(); System.out.print("  User              : "); app.showUserHistory(sc.nextLine().trim()); break;
                    case 8: app.showAllTransactions(); break;
                    case 9: System.out.print("  K = "); app.showTopKUsers(Integer.parseInt(sc.nextLine().trim())); break;
                    case 10: System.out.print("  Sort (ASC/DESC)   : "); app.showBalanceReport(sc.nextLine().trim()); break;
                    case 11: app.showAllUsers(); break;
                    case 12: printIdHint(); System.out.print("  User to delete    : "); app.deleteUser(sc.nextLine().trim()); break;
                    case 13: app.showPendingTransfers(); break;
                    case 14: app.showAllRewards(); break;
                    case 15: printIdHint(); System.out.print("  User              : "); app.showUserRewards(sc.nextLine().trim()); break;
                    case 16:
                        printIdHint();
                        System.out.print("  Creator (or SYSTEM): "); String creator = sc.nextLine().trim();
                        System.out.print("  Gift card amount  : "); double gamt    = Double.parseDouble(sc.nextLine().trim());
                        app.generateGiftCard(creator, gamt); break;
                    case 17:
                        printIdHint();
                        System.out.print("  Redeemer          : "); String rdm  = sc.nextLine().trim();
                        System.out.print("  Gift card code    : "); String code = sc.nextLine().trim();
                        app.redeemGiftCard(rdm, code); break;
                    case 18: System.out.print("  Show (ALL/ACTIVE) : "); app.showGiftCards(sc.nextLine().trim().equalsIgnoreCase("ACTIVE")); break;
                    case 19: printIdHint(); System.out.print("  User              : "); app.showMyGiftCards(sc.nextLine().trim()); break;
                    case 20:
                        app.saveUsersCSV(); app.saveTxnCSV(); app.saveGiftCardsCSV();
                        System.out.println("  OK All data saved. Goodbye!"); break;
                    default: System.out.println("  X Invalid choice (1-20).");
                }
            } catch (NumberFormatException e) { System.out.println("  X Invalid input."); choice = 0; }
        } while (choice != 20);
        sc.close();
    }

    private static void printBanner() {
        System.out.println();
        System.out.println("  +=============================================================+");
        System.out.println("  |          PhonePe  Digital Wallet System                     |");
        System.out.println("  |  HashMap . Queue . Stack . ArrayList . Heap . Sorting       |");
        System.out.println("  |       + Reward Engine (every 1000 txn, Rs.1-100)            |");
        System.out.println("  |       + Gift Card System                                    |");
        System.out.println("  +=============================================================+");
        System.out.println();
    }

    private static void printMenu() {
        System.out.println();
        System.out.println("  +=============================================================+");
        System.out.println("  |                         M E N U                             |");
        System.out.println("  +=============================================================+");
        System.out.println("  |  Lookup by: userId (U1001) / mobile / name                  |");
        System.out.println("  +-------------------------------------------------------------+");
        System.out.println("  |  --- WALLET ---                                             |");
        System.out.println("  |  1.  Register User                                          |");
        System.out.println("  |  2.  Add Money to Wallet                                    |");
        System.out.println("  |  3.  Transfer Money                                         |");
        System.out.println("  |  4.  Process Transfer                                       |");
        System.out.println("  |  5.  Undo Last Transaction                                  |");
        System.out.println("  |  6.  Check Balance                                          |");
        System.out.println("  |  7.  My Transaction History                                 |");
        System.out.println("  |  8.  All Transactions                                       |");
        System.out.println("  |  9.  Top-K Wallet Holders   (Heap)                          |");
        System.out.println("  |  10. Balance Report         (Sort ASC/DESC)                 |");
        System.out.println("  |  11. Show All Users                                         |");
        System.out.println("  |  12. Delete User                                            |");
        System.out.println("  |  13. View Pending Transfers                                 |");
        System.out.println("  +-------------------------------------------------------------+");
        System.out.println("  |  --- REWARDS  (auto every 1000th txn, Rs.1-100 cashback)  --|");
        System.out.println("  |  14. View All Rewards                                       |");
        System.out.println("  |  15. View My Rewards                                        |");
        System.out.println("  +-------------------------------------------------------------+");
        System.out.println("  |  --- GIFT CARDS ---                                         |");
        System.out.println("  |  16. Generate Gift Card  (user or SYSTEM)                   |");
        System.out.println("  |  17. Redeem Gift Card                                       |");
        System.out.println("  |  18. View All Gift Cards  (ALL / ACTIVE)                    |");
        System.out.println("  |  19. View My Gift Cards                                     |");
        System.out.println("  +-------------------------------------------------------------+");
        System.out.println("  |  20. Save & Exit                                            |");
        System.out.println("  +=============================================================+");
    }

    private static void printIdHint() {
        System.out.println("  (Enter userId e.g. U1001 / mobile / name)");
    }
}